name: crypto-rate
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./internal/adapters/storage/migrations:/docker-entrypoint-initdb.d
      - C:\data:/var/lib/postgresql/data
    ports:
      - 5434:5432